#!/usr/bin/env node
const kodelang = require('./src/kodelang')
const fs = require('fs')

function promisify(fn, ...args) {
	return new Promise((resolve, reject) => fn(...args, (err, result) => {
		if (err) {
			reject(err)
		} else {
			resolve(result)
		}
	}))
}

const filename = process.argv[2]

promisify(fs.readFile, filename, 'utf-8')
.then(kodelang.compile)
.then(code => promisify(fs.writeFile, filename.replace('.kodelang', '.js'), code))
.then(null, e => {
	console.error(e)
	process.exit(1)
})
